[package]
name = "not-fs-loader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
not-fs-core = { path = "../not-fs-core" }
not-fs-ram = { path = "../not-fs-ram" }
lazy_static = "1.4.0"

